name: "Setup rv"
description: "Set up your GitHub Actions workflow with rv"
author: "spinel-coop"
branding:
  icon: "box"
  color: "red"

inputs:
  ruby-version:
    description: "Ruby version to install (e.g. '3.4.2' or 'current' to read .ruby-version). Omit to skip."
    required: false
  gems-clean-install:
    description: "Run 'rv ci' and cache installed gems"
    required: false
    default: "false"
  working-directory:
    description: "Directory containing Gemfile and/or .ruby-version"
    required: false
    default: "."
  enable-cache:
    description: "Cache rv's download cache (~/.cache/rv)"
    required: false
    default: "auto"
  cache-version:
    description: "Increment to invalidate the gem cache"
    required: false
    default: "0"

outputs:
  rv-version:
    description: "The installed rv version"
    value: ${{ steps.install-rv.outputs.rv-version }}
  ruby-version:
    description: "The installed Ruby version"
    value: ${{ steps.install-ruby.outputs.ruby-version }}
  cache-hit:
    description: "Whether the gem cache was restored exactly"
    value: ${{ steps.gem-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    # Always: cache rv's download cache
    - name: Restore rv download cache
      if: inputs.enable-cache != 'false'
      uses: actions/cache@v5
      with:
        path: ~/.cache/rv
        key: setup-rv-${{ runner.os }}-${{ runner.arch }}

    # Always: install rv
    - name: Install rv
      id: install-rv
      shell: bash
      run: ${{ github.action_path }}/action.sh install-rv

    # Optional: install Ruby (only when ruby-version is provided)
    - name: Install Ruby
      id: install-ruby
      if: inputs.ruby-version != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        RUBY_VERSION: ${{ inputs.ruby-version }}
      run: ${{ github.action_path }}/action.sh install-ruby

    # Optional: cache gems (only when gems-clean-install is true)
    - name: Cache gems
      id: gem-cache
      if: inputs.gems-clean-install == 'true'
      uses: actions/cache@v5
      with:
        path: ${{ inputs.working-directory }}/vendor/bundle
        key: setup-rv-gems-v${{ inputs.cache-version }}-${{ runner.os }}-${{ runner.arch }}-ruby-${{ steps.install-ruby.outputs.ruby-version }}-${{ hashFiles(format('{0}/Gemfile.lock', inputs.working-directory)) }}
        restore-keys: |
          setup-rv-gems-v${{ inputs.cache-version }}-${{ runner.os }}-${{ runner.arch }}-ruby-${{ steps.install-ruby.outputs.ruby-version }}-

    # Optional: install gems (only when gems-clean-install is true)
    - name: Install gems
      if: inputs.gems-clean-install == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ github.action_path }}/action.sh install-gems
